const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('erpApi', {
  getBootstrap: () => ipcRenderer.invoke('erp:get-bootstrap'),
  getLicenseStatus: () => ipcRenderer.invoke('erp:get-license-status'),
  activateLicenseKey: (payload) => ipcRenderer.invoke('erp:activate-license-key', payload),
  closeApp: () => ipcRenderer.invoke('erp:close-app'),
  upsertUiSettings: (payload) => ipcRenderer.invoke('erp:upsert-ui-settings', payload),
  upsertBusiness: (payload) => ipcRenderer.invoke('erp:upsert-business', payload),
  getBackupSettings: () => ipcRenderer.invoke('erp:get-backup-settings'),
  upsertBackupSettings: (payload) => ipcRenderer.invoke('erp:upsert-backup-settings', payload),
  pickBackupFolder: (currentPath) => ipcRenderer.invoke('erp:pick-backup-folder', currentPath),
  runLocalBackup: () => ipcRenderer.invoke('erp:run-local-backup'),
  restoreLatestLocalBackup: () => ipcRenderer.invoke('erp:restore-latest-local-backup'),

  upsertProduct: (payload) => ipcRenderer.invoke('erp:upsert-product', payload),
  lookupOpenFoodFactsProduct: (payload) => ipcRenderer.invoke('erp:lookup-open-food-facts-product', payload),
  deleteProduct: (productId) => ipcRenderer.invoke('erp:delete-product', productId),

  upsertCustomer: (payload) => ipcRenderer.invoke('erp:upsert-customer', payload),
  deleteCustomer: (customerId) => ipcRenderer.invoke('erp:delete-customer', customerId),

  upsertSupplier: (payload) => ipcRenderer.invoke('erp:upsert-supplier', payload),
  deleteSupplier: (supplierId) => ipcRenderer.invoke('erp:delete-supplier', supplierId),

  createInvoice: (payload) => ipcRenderer.invoke('erp:create-invoice', payload),
  updateInvoice: (payload) => ipcRenderer.invoke('erp:update-invoice', payload),
  recordInvoicePayment: (payload) => ipcRenderer.invoke('erp:record-invoice-payment', payload),
  createPurchase: (payload) => ipcRenderer.invoke('erp:create-purchase', payload),
  updatePurchase: (payload) => ipcRenderer.invoke('erp:update-purchase', payload),
  upsertGstNote: (payload) => ipcRenderer.invoke('erp:upsert-gst-note', payload),
  deleteGstNote: (noteId) => ipcRenderer.invoke('erp:delete-gst-note', noteId),
  recordGstFiling: (payload) => ipcRenderer.invoke('erp:record-gst-filing', payload),
  unlockGstPeriod: (payload) => ipcRenderer.invoke('erp:unlock-gst-period', payload),
  createSupplierPayment: (payload) => ipcRenderer.invoke('erp:create-supplier-payment', payload),
  createExpense: (payload) => ipcRenderer.invoke('erp:create-expense', payload),
  updateExpense: (payload) => ipcRenderer.invoke('erp:update-expense', payload),
  extractEnglishOcr: (payload) => ipcRenderer.invoke('erp:extract-english-ocr', payload),
  getCustomerLedger: (customerId) => ipcRenderer.invoke('erp:get-customer-ledger', customerId),
  getSupplierLedger: (supplierId) => ipcRenderer.invoke('erp:get-supplier-ledger', supplierId),
  getTrialBalance: (payload) => ipcRenderer.invoke('erp:get-trial-balance', payload),
  getDailyProfitLoss: (inputDate) => ipcRenderer.invoke('erp:get-daily-pnl', inputDate),
  getGstFilingData: (payload) => ipcRenderer.invoke('erp:get-gst-filing-data', payload),
  getGstPortalExport: (payload) => ipcRenderer.invoke('erp:get-gst-portal-export', payload),
  saveExportFile: (payload) => ipcRenderer.invoke('erp:save-export-file', payload),
  getPrinters: () => ipcRenderer.invoke('erp:get-printers'),
  autoPrintInvoiceThermal: (payload) => ipcRenderer.invoke('erp:auto-print-invoice-thermal', payload),
  getInvoice: (invoiceId) => ipcRenderer.invoke('erp:get-invoice', invoiceId),
  previewInvoice: (invoiceId, options) => ipcRenderer.invoke('erp:preview-invoice', invoiceId, options),
  printInvoice: (invoiceId) => ipcRenderer.invoke('erp:print-invoice', invoiceId),
  exportStockListPdf: () => ipcRenderer.invoke('erp:export-stock-list-pdf')
});
